### ISSUE TITLE
ENOTEMPTY

### ISSUE THREAD

**Issue by ffMathy** [sindresorhus/move-file-cli#4]
Hi Sindre! Big fan.

Getting this error when using the CLI:

```
Error: ENOTEMPTY: directory not empty, rename '/Users/foo/Documents/src/poodle.lol/.vercel/output/functions/_qwik-city.func' -> '/Users/foo/Documents/src/poodle.lol/output/static'
    at Object.renameSync (node:fs:1040:3)
    at _moveFileSync (file:///Users/foo/Documents/src/poodle.lol/node_modules/move-file/index.js:77:6)
    at moveFileSync (file:///Users/foo/Documents/src/poodle.lol/node_modules/move-file/index.js:95:9)
    at file:///Users/foo/Documents/src/poodle.lol/node_modules/move-file-cli/cli.js:26:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  errno: -66,
  syscall: 'rename',
  code: 'ENOTEMPTY',
  path: '/Users/foo/Documents/src/poodle.lol/.vercel/output/functions/_qwik-city.func',
  dest: '/Users/foo/Documents/src/poodle.lol/output/static'
```

**Comment by ffMathy** [comment]
I would expect `move-file-cli` to merge my source folder into the destination, if the destination is not empty.

Or make it configurable.

**Comment by sindresorhus** [comment]
This CLI only handles moving a single file. That's intentional. I didn't want to deal with the complexity of handling directories (and merging, etc). I think you're looking for a more advanced CLI. I have added a readme note to make it clear.
